#!/bin/bash

cd ../ && \
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 5*.c 0-hash_table_create.c 1-djb2.c 2-key_index.c 3-hash_table_set.c 4-hash_table_get.c -o 5-print && \
valgrind --leak-check=full --show-leak-kinds=all ./5-print